services:
  #---------------
  # PostgresSQL Database
  #---------------
  db:
    image: postgres:17.1
    container_name: Customer_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
      POSTGRES_DB: ${DB_NAME_SECRET}
    ports:
      - ${DB_PORT_SECRET}:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Customer_network
  db2:
    image: postgres:17.1
    container_name: Orders_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB2_USER}
      POSTGRES_PASSWORD: ${DB2_PASS}
      POSTGRES_DB: ${DB2_NAME}
    ports:
      - ${DB2_PORT}:5432
    volumes:
      - "./DB339618100_217372119/שלב ג:/docker-entrypoint-initdb.d"
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - Customer_network
  #----------------
  # pgAdmin
  #---------------- 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdminApp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
      - db2
    networks:
      - Customer_network
#----------------
# Network
#----------------
networks:
  Customer_network:
    #    driver: bridge
    #----------------
    # Volumes
    #---------------- 
volumes:
  postgres_data:
  postgres_data2:
  pgadmin_data:
