CREATE TABLE GANENET
(
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL UNIQUE,
  Email VARCHAR(255) UNIQUE,
  CONSTRAINT chk_email CHECK (Email LIKE '%@%')
);

CREATE TABLE YELED
(
  Child_ID SERIAL PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Age SMALLINT NOT NULL,
  Parent_Phone VARCHAR(20) NOT NULL,
  Allergies TEXT,
  Ganennet_ID INT NOT NULL, 
  FOREIGN KEY (Ganennet_ID) REFERENCES GANENET(ID),
  
  CONSTRAINT chk_age CHECK (Age >= 0 AND Age <= 6)
);