-- 1. Verify Lookup Tables
SELECT * FROM STATUS_TYPE;
SELECT * FROM LOYALTY_TIER;
SELECT * FROM REASON;

-- 2. Verify Core Entities
SELECT * FROM CUSTOMER;

-- 3. Verify Transactional/Dependent Tables
SELECT * FROM RESERVATION;
SELECT * FROM WAITLIST;
SELECT * FROM FEEDBACK;
SELECT * FROM LOYALTY;
SELECT * FROM LOYALTY_TRANSACTION;